// <auto-generated />
using System;
using JJs.UnitsManagement.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JJs.UnitsManagement.MigrationService.Migrations
{
    [DbContext(typeof(UnitsManagementDbContext))]
    partial class UnitsManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Unit")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JJs.UnitsManagement.Infrastructure.Entities.SyncJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The unique identifier for the sync job");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("When the job completed");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Sync configuration as JSON");

                    b.Property<bool>("CreateNew")
                        .HasColumnType("bit")
                        .HasComment("Whether to create new records");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("When the job was created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System")
                        .HasComment("Who created the sync job");

                    b.Property<string>("CurrentEntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Current entity type being processed");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Current step being processed");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Error message if the job failed");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("int")
                        .HasComment("Number of items processed in current step");

                    b.Property<string>("JobName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Optional name for the job");

                    b.Property<int>("OverallProgress")
                        .HasColumnType("int")
                        .HasComment("Overall progress percentage (0-100)");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Final sync results as JSON (when completed)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("datetimeoffset")
                        .HasComment("When the job started processing");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Current status of the job");

                    b.Property<string>("StatusMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Status message");

                    b.Property<bool>("SyncUnits")
                        .HasColumnType("bit")
                        .HasComment("Whether to sync units");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int")
                        .HasComment("Total number of items in current step");

                    b.Property<bool>("UpdateExisting")
                        .HasColumnType("bit")
                        .HasComment("Whether to update existing records");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("When the sync job was last updated");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System")
                        .HasComment("Who last updated the sync job");

                    b.HasKey("JobId");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("IX_SyncJobs_CompletedAt");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_SyncJobs_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SyncJobs_Status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_SyncJobs_Status_CreatedAt");

                    b.ToTable("SyncJobs", "Unit");
                });

            modelBuilder.Entity("JJs.UnitsManagement.Infrastructure.Entities.Unit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("The unique identifier for the unit");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasComment("Determines if the unit is active or not");

                    b.Property<string>("Activity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Activity or operational area (from ACTIVITY field)");

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Chassis number (from CHASSIS_NUMBER field)");

                    b.Property<string>("Company")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Company code for organisation linkage (from COMPANY field)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Country code (from COUNTRY_CODE field)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("When the unit was created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("System")
                        .HasComment("Who created the unit");

                    b.Property<string>("DCN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("DCN identifier (from DCN field)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Department within the company (from DEPARTMENT field)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Description of the unit (from DESCRIPTION field)");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Engine number (from ENGINE_NUMBER field)");

                    b.Property<string>("EuroType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Euro emission standard type (from EURO_TYPE field)");

                    b.Property<string>("Extra")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Additional information (from EXTRA field)");

                    b.Property<string>("Make")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Vehicle make (extracted from TRUCK_MODEL field)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Vehicle model (from TRUCK_MODEL field)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("Vehicle registration number (from REGISTRATION_NUMBER field)");

                    b.Property<string>("State")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("State or territory where unit operates (from STATE field)");

                    b.Property<string>("TruckNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The truck number (business key from TRUCK_NUMBER field)");

                    b.Property<int?>("TruckType")
                        .HasColumnType("int")
                        .HasComment("Type of truck for operational classification (from TRUCK_TYPE field)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasComment("When the unit was last updated");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Who last updated the unit");

                    b.Property<DateTime?>("WarrantyDate")
                        .HasColumnType("datetime2")
                        .HasComment("Warranty expiration date (from WARRANTY_DATE field)");

                    b.HasKey("UnitId");

                    b.HasIndex("Active")
                        .HasDatabaseName("IX_Units_Active");

                    b.HasIndex("Company")
                        .HasDatabaseName("IX_Units_Company");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Units_CreatedAt");

                    b.HasIndex("RegistrationNumber")
                        .HasDatabaseName("IX_Units_RegistrationNumber");

                    b.HasIndex("State")
                        .HasDatabaseName("IX_Units_State");

                    b.HasIndex("TruckNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Units_TruckNumber");

                    b.HasIndex("TruckType")
                        .HasDatabaseName("IX_Units_TruckType");

                    b.HasIndex("Active", "TruckType", "Company")
                        .HasDatabaseName("IX_Units_Active_TruckType_Company");

                    b.ToTable("Units", "Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
