n: 1.0.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  account_feed: true
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet --version

    dotnet restore ./modeller/src/modeller.base/hy.modeller.base.csproj

    dotnet restore ./modeller/src/modeller.core/hy.modeller.core.csproj

    dotnet restore ./modeller/src/modeller.fluent/hy.modeller.fluent.csproj

    dotnet restore ./modeller/tests/modeller.Tests/modeller.tests.csproj

    dotnet restore ./modeller/tests/TestGenerator/testgenerator.csproj
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
artifacts:
- path: '**/*.nupkg'
notifications:
- provider: Email
  to:
  - allan.nielsen@jbssa.com.au
  - imathome@zoho.com
  subject: Modeller build failed
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false